import { HistoryRepository } from '../repositories/history.repository';
import { QueryCacheService } from './queryCache.service';
import { SqlService } from '../ai/sql.service';
import { OpenRouterService } from '../ai/openrouter.service';
import { Message } from '../types/history';

export class ChatbotService {
  private historyRepo = new HistoryRepository();
  private queryCache = new QueryCacheService();
  private sqlService = new SqlService();
  private openRouter = new OpenRouterService();

  public async processMessage(
    conversationId: string,
    messageText: string,
    model: string,
    userNIK: string = 'VOK001'
  ): Promise<{
    success: boolean;
    message: Message;
    sqlQuery: string | null;
    sqlResult: any;
    sqlError?: string;
    fromLearning: boolean;
  }> {
    console.log(`\n======================================================`);
    console.log(`[PIPELINE] 🚀 MEMULAI PROSES PESAN BARU`);
    console.log(`[PIPELINE] Pesan User : "${messageText}"`);
    console.log(`[PIPELINE] User NIK   : ${userNIK}`);
    console.log(`======================================================`);

    // 1. Fetch current conversation-scoped AI Memories (Passive Memory)
    console.log(`[PIPELINE] 1. Mengambil Konteks Memori (AI Memories)...`);
    const memories = await this.historyRepo.getMemories(conversationId);
    const memoryContext = memories.length > 0
      ? memories.map((m, i) => `${i+1}. ${m.FactText}`).join('\n')
      : 'Belum ada fakta personal atau konteks yang diingat dalam percakapan ini.';

    // 2. Fetch history of the current conversation (last 6 messages for context)
    const rawHistory = await this.historyRepo.getMessages(conversationId);
    const history = rawHistory.slice(-6);
    const historyContext = history.length > 0
      ? history.map(h => `${h.Sender}: ${h.MessageText}`).join('\n')
      : 'Sesi baru dimulai.';

    // 3. Detect Passive Context and Data download/export requests
    const isDownloadRequest = /download|export|unduh|cetak|print/i.test(messageText);
    let sqlQuery: string | null = null;
    let sqlResult: any = null;
    let sqlError: string | undefined;
    let fromLearning = false;
    let vocabularyContext = '';

    if (isDownloadRequest) {
      // Find the last message in this conversation that has an SQL query and result
      const allMessages = await this.historyRepo.getMessages(conversationId);
      const lastSqlMessage = [...allMessages].reverse().find(m => m.SqlQuery && m.SqlResult);
      if (lastSqlMessage) {
        sqlQuery = lastSqlMessage.SqlQuery || null;
        try {
          sqlResult = JSON.parse(lastSqlMessage.SqlResult!);
        } catch (e) {
          sqlResult = null;
        }
        console.log(`[ChatbotService] Restored passive context download request: ${sqlQuery}`);
      }
    }

    // 4. Memory extraction for personal declarations
    const cleanMsg = messageText.trim().toLowerCase();
    if (
      cleanMsg.includes('nama saya') ||
      cleanMsg.includes('saya bekerja di') ||
      cleanMsg.includes('saya di departemen') ||
      cleanMsg.includes('nik saya')
    ) {
      console.log(`[PIPELINE] 2. Keyword memori terdeteksi! Mengeksekusi ekstraksi secara asinkron (Background)...`);
      // FIRE AND FORGET: Jangan biarkan ini memblokir loading utama pengguna
      const extractionPrompt = `Analisis kalimat berikut dan cari tahu apakah pengguna menyebutkan informasi personal baru tentang diri mereka sendiri seperti Nama, NIK, Departemen, atau Jabatan. Jika ada, sebutkan fakta tersebut dalam 1 kalimat pendek berformat bahasa Indonesia (contoh: "Nama pengguna adalah Gohan" atau "Pengguna bekerja di departemen IT"). Jika tidak ada fakta baru, kembalikan kata "NONE".
Kalimat pengguna: "${messageText}"`;

      this.openRouter.generateContent(extractionPrompt)
        .then(async (extractedFact) => {
          if (extractedFact && !extractedFact.toUpperCase().includes('NONE') && extractedFact.length > 3) {
            await this.historyRepo.addMemory(extractedFact, userNIK, conversationId);
            console.log(`[ChatbotService] Auto-saved extracted personal fact: ${extractedFact}`);
          }
        })
        .catch(err => console.error('Error during automatic fact extraction:', err));
    }

    // Add user message to persistent DB history
    await this.historyRepo.addMessage(conversationId, 'User', messageText);

    // 5. Vocabulary hints only. SQL is always generated by AI.
    console.log(`[PIPELINE] 3. Mengambil petunjuk kosakata AI...`);
    const vocabularyHints = await this.queryCache.getVocabularyHints(messageText);
    vocabularyContext = vocabularyHints.length
      ? `\nKoreksi kosakata yang pernah dipelajari:\n${vocabularyHints.join('\n')}`
      : '';

    // 6. SQL query drafting & verification via LLM if not retrieved from cache
    let sqlErrorFromGen: string | undefined;
    if (!sqlQuery) {
      console.log(`[PIPELINE] 4. Merancang SQL dengan Model LLM (${model})...`);
      try {
        const sqlRes = await this.sqlService.generateSql(messageText, memoryContext, `${historyContext}${vocabularyContext}`, model);
        if (sqlRes.requiresQuery && sqlRes.sql) {
          sqlQuery = sqlRes.sql;
          console.log(`[PIPELINE]    -> ✅ LLM merumuskan SQL: ${sqlQuery}`);
        } else {
          console.log(`[PIPELINE]    -> ℹ️ LLM memutuskan tidak perlu SQL (General Chat)`);
        }
      } catch (err: any) {
        console.error('[PIPELINE]    -> ❌ Error in SQL generation pipeline:', err);
        sqlErrorFromGen = `Gagal merancang kueri otomatis: ${err.message}`;
      }
    }

    // 7. Execute SQL Query safely against the simulated engine
    if (sqlQuery && !sqlResult) {
      console.log(`[PIPELINE] 5. Mengeksekusi Kueri SQL ke Database...`);
      const queryRes = await this.historyRepo.executeSQL(sqlQuery);
      if (queryRes.success) {
        sqlResult = queryRes.data;
        console.log(`[PIPELINE]    -> ✅ Database merespons. Jumlah baris: ${Array.isArray(sqlResult) ? sqlResult.length : 1}`);
      } else {
        sqlError = queryRes.error;
        console.log(`[PIPELINE]    -> ❌ Database Error: ${sqlError}`);
      }
    }

    if (sqlErrorFromGen) {
      sqlError = sqlError ? `${sqlErrorFromGen} | ${sqlError}` : sqlErrorFromGen;
    }

    // 8. Generate Human-Friendly Synthesized Summary Response
    let summarizationSystem = `Kamu adalah Smart IT Assistant PT Voksel Electric Tbk. Jawab dalam Bahasa Indonesia, ringkas dan profesional.
ATURAN KETAT:
- HANYA jika input pengguna merupakan sapaan (halo/hai/hi), balas hangat dan gunakan emoji 👋.
- Untuk input data, DILARANG membuka dengan "Halo", sapaan, atau emoji.
- Ada data DB: Tulis ringkasan naratif + maks 3 insight. DILARANG menulis daftar data atau tabel Markdown. Frontend sudah tampilkan tabel & grafik otomatis.
- Semua angka, mayoritas, persentase, tahun, merek, departemen, dan kesimpulan harus dapat dihitung langsung dari baris data yang diberikan.
- Jika preview ditandai terpotong, jangan menyimpulkan distribusi seluruh data. Cukup sebut total baris dan informasi yang pasti.
- Jika SQL bukan query agregasi (tidak memiliki COUNT/SUM/AVG/GROUP BY), jawab maksimal 2 kalimat: sebut jumlah baris yang ditemukan dan bahwa rinciannya tersedia pada tabel interaktif. DILARANG menghitung persentase, mayoritas, merek dominan, departemen dominan, atau kesimpulan lain.
- Insight statistik hanya boleh dibuat jika SQL memang query agregasi COUNT/SUM/AVG/GROUP BY.
- Tidak ada data: Jawab pertanyaan dengan pengetahuan umum secara cerdas.
- Jawaban maks 150 kata.`;

    let sqlResultPreview = 'Tidak ada hasil';
    if (sqlResult && Array.isArray(sqlResult)) {
      const columns = sqlResult.length > 0 ? Object.keys(sqlResult[0]) : [];
      const previewLimit = 50;
      const isTruncated = sqlResult.length > previewLimit;
      sqlResultPreview = JSON.stringify({
        totalRowsCount: sqlResult.length,
        columns: columns,
        isTruncated,
        note: isTruncated
          ? "Preview hanya sebagian. Jangan membuat klaim mayoritas, persentase, atau distribusi untuk seluruh data."
          : "Preview memuat seluruh hasil. Insight boleh dihitung hanya dari baris ini.",
        rows: sqlResult.slice(0, previewLimit)
      });
    } else if (sqlResult) {
      sqlResultPreview = JSON.stringify(sqlResult);
    }

    const summaryPrompt = `
Kalimat Pengguna: "${messageText}"
Kueri SQL yang dijalankan: ${sqlQuery || 'Tidak ada kueri SQL'}
Hasil Eksekusi Database (Preview): ${sqlResultPreview}
Kesalahan Database (jika ada): ${sqlError || 'Tidak ada kesalahan'}
Informasi AI Memory:
${memoryContext}

Tulis tanggapan akhir yang profesional dan informatif dalam Bahasa Indonesia.`;

    const isAggregateQuery = Boolean(
      sqlQuery && (/\b(?:COUNT|SUM|AVG|MIN|MAX)\s*\(/i.test(sqlQuery) || /\bGROUP\s+BY\b/i.test(sqlQuery))
    );
    let effectiveSummaryPrompt = summaryPrompt;
    if (sqlQuery && Array.isArray(sqlResult) && !isAggregateQuery) {
      summarizationSystem = `Kamu adalah formatter respons data.
Balas tepat satu kalimat sesuai instruksi pengguna. Dilarang menambah angka,
tanggal, merek, status, persentase, analisis, sapaan, emoji, atau insight.`;
      effectiveSummaryPrompt = `Tulis tepat satu kalimat berikut tanpa perubahan:
"Ditemukan ${sqlResult.length} baris data yang sesuai. Rincian lengkap tersedia pada tabel interaktif."`;
    }

    let finalAnswer = 'Maaf, saya tidak dapat merumuskan tanggapan saat ini.';
    const isGraphRequest = /grafik|chart|diagram|plot|visualisasi/i.test(messageText);

    if (sqlError && !sqlResult) {
      finalAnswer = `Maaf, permintaan belum dapat diproses karena layanan data mengalami gangguan. ${sqlError}`;
    } else if (isGraphRequest && sqlResult && Array.isArray(sqlResult) && sqlResult.length > 0) {
      // User requested a graph and data is available. Skip the LLM small-talk completely.
      console.log(`[PIPELINE] 6. (Dilewati) Pengguna meminta grafik, LLM summarization tidak diperlukan.`);
      finalAnswer = '';
    } else {
      try {
        console.log(`[PIPELINE] 6. Merumuskan Tanggapan Akhir (Summarization)...`);
        finalAnswer = await this.openRouter.generateContent(effectiveSummaryPrompt, summarizationSystem, false, model, 400);
        console.log(`[PIPELINE]    -> ✅ Tanggapan siap.`);
      } catch (err: any) {
        console.error('[PIPELINE]    -> ❌ Error generating response summary:', err);
        if (Array.isArray(sqlResult)) {
          finalAnswer = sqlResult.length > 0
            ? `Ditemukan ${sqlResult.length} baris data yang sesuai. Hasil lengkap tersedia pada tabel interaktif.`
            : 'Tidak ditemukan data yang sesuai dengan permintaan.';
        } else {
          finalAnswer = `Maaf, terjadi kesalahan saat merumuskan tanggapan: ${err.message}`;
        }
      }
    }

    // 9. Persist AI Response in the Conversation History
    const aiMsg = await this.historyRepo.addMessage(
      conversationId,
      'AI',
      finalAnswer,
      sqlQuery || undefined,
      sqlResult || undefined,
      350 // Mock token usage
    );

    return {
      success: true,
      message: aiMsg,
      sqlQuery,
      sqlResult,
      sqlError,
      fromLearning
    };
  }
}
